ARG PHP_VERSION
FROM php:${PHP_VERSION}-fpm


# Install system dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxml2-dev \
    libxslt-dev \
    libzip-dev \
    libssl-dev \
    git vim unzip cron \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Install FTP extension
RUN docker-php-ext-configure ftp --with-ftp-ssl \
	&& docker-php-ext-install ftp

# GD extension
RUN docker-php-ext-configure gd \
    --with-jpeg \
    --with-freetype && \
    docker-php-ext-install -j$(nproc) gd

    
# Install intl
RUN docker-php-ext-configure intl && \
    docker-php-ext-install -j$(nproc) intl

# Install other common extensions
RUN docker-php-ext-install -j$(nproc) \
    opcache bcmath pdo_mysql soap xsl zip sockets mysqli

# Install Redis
RUN pecl install redis \
	&& docker-php-ext-enable redis

# Install memecached
RUN apt-get update && apt-get install -y libmemcached-dev zlib1g-dev \
	&& pecl install memcached \
	&& docker-php-ext-enable memcached

# Xdebug installation
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN mkdir -p /xdebug/profiles && chmod -R 0777 /xdebug/profiles

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

ENV COMPOSER_HOME=/composer
ENV PATH="${COMPOSER_HOME}/vendor/bin:${PATH}"

# Install Laravel Installer
RUN composer global require laravel/installer

# Add NodeSource Node.js 18.x repo (or change to the version you need)
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -

# Install Node.js (includes npm and npx)
RUN apt-get install -y nodejs npm

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

RUN apt-get update && apt-get install -y \
    less nano vim unzip git curl wget procps \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Copy custom PHP config
COPY ./php-custom.ini "$PHP_INI_DIR/conf.d/custom.ini"

# Set default php.ini (development config)
RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

ARG UID
ARG GID

RUN groupadd -g ${GID} appuser \
 && useradd -u ${UID} -g appuser -m appuser

USER appuser
WORKDIR /var/www/html

EXPOSE 9000

CMD ["php-fpm"]
