zend_extension=xdebug

# xdebug.mode = debug,develop,profile,trace
xdebug.mode=profile,trace
xdebug.start_with_request=trigger
xdebug.client_host=192.168.1.30
xdebug.discover_client_host=false
xdebug.use_compression=false
xdebug.log=/tmp/xdebug.log
xdebug.output_dir=/xdebug/profiles
xdebug.collect_params=1
xdebug.trace_options=0x08
xdebug.trace_format=0
xdebug.collect_return=1
xdebug.trace_output_name=default-fpm-%H-%R-%r.trace
