version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - ${PORT_HTTP:-80}:80
      - ${PORT_HTTPS:-443}:443
    volumes:
      - "${CONF_DIR:-./config.d}:/etc/nginx/conf.d"
      - "${CERT_DIR:-./certs}:/etc/nginx/certs:ro"
      - "${PROJECT_DIR:-/home/ben/projects}:/var/www"
    networks:
      - ben

networks:
  ben:
    external: true