zend_extension=xdebug.so

[xdebug]
; Xdebug 3.x configuration
xdebug.mode = ${XDEBUG_MODE}
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = PHPSTORM

; Logging
xdebug.log = /var/log/php/xdebug.log
xdebug.log_level = 7

; Profiling
xdebug.output_dir = /xdebug
xdebug.profiler_output_name = cachegrind.out.%t.%p

; Tracing
xdebug.trace_output_name = trace.%t.%p

; Coverage
xdebug.coverage_enable = 1

; Step debugging
xdebug.max_nesting_level = 512
