# server {
#   listen 443 ssl;
#   server_name cafe3co.local;
#   ssl_certificate     /etc/nginx/certs/_wildcard.local+1.pem;
#   ssl_certificate_key /etc/nginx/certs/_wildcard.local+1-key.pem;
  
#   location / {
#     proxy_pass http://varnish:80;

#     proxy_http_version 1.1;

#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

#     # 🔥 QUAN TRỌNG cho Magento
#     proxy_set_header X-Forwarded-Proto https;
#     proxy_set_header X-Forwarded-Port 443;

#     # 🔥 FIX LỖI HEADER TOO BIG
#     proxy_buffer_size 128k;
#     proxy_buffers 4 256k;
#     proxy_busy_buffers_size 256k;

#     # tránh lỗi connection reuse
#     proxy_set_header Connection "";
#   }
# }

server {
  listen 80;
  server_name cafe3co.local cafe3co.benthunder.io.vn;
  set $MAGE_ROOT /var/www/cafe3co;
  include /var/www/cafe3co/nginx.conf;
}
