server {
  listen 443 ssl;
  server_name cafe3co.local;
  ssl_certificate     /etc/nginx/certs/_wildcard.local+1.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.local+1-key.pem;
  set $MAGE_ROOT /var/www/cafe3co;
  include /var/www/cafe3co/nginx.conf;
}

server {
  listen 80;
  server_name cafe3co.benthunder.io.vn;
  set $MAGE_ROOT /var/www/cafe3co;
  include /var/www/cafe3co/nginx.conf;
}
