server {
  listen 443 ssl;
  server_name mage2.local;
  set $MAGE_ROOT /var/www/mage2/html;
  include /var/www/mage2/html/nginx.conf;
}

server {
  listen 80;
  server_name mage2.benthunder.io.vn;
  set $MAGE_ROOT /var/www/mage2/html;
  include /var/www/mage2/html/nginx.conf;
}
