server {
    listen 80;
    server_name thaison.local thaison.benthunder.io.vn;

    root /var/www/thaison/html;
    index index.php index.html;

    charset utf-8;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # WordPress permalink
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # favicon / robots
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # deny hidden files
    location ~ /\. {
        deny all;
    }

    # deny PHP in uploads
    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    # static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp)$ {
        expires 30d;
        access_log off;
        log_not_found off;
    }

    # PHP handling
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass php84-fpm:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;

        fastcgi_hide_header X-Powered-By;
    }
}